
services:

  # Supporting Containers

  mongo:
    image: mongo:6.0.9
    user: ${ELEMENTS_UID}:${ELEMENTS_GID}
    command:
      - mongod
      - --replSet
      - local-test
    deploy:
      replicas: 1
    networks:
      - elements
    ports:
      - "27017:27017"
    volumes:
      - ${DB_HOST_DIR:-./volume/mongo/db/data}:/data/db

  rs-init:
    build:
      context: rs-init
    user: ${ELEMENTS_UID}:${ELEMENTS_GID}
    deploy:
      replicas: 1
    networks:
      - elements

  # Elements Containers

  ws:
    build:
      context: ./ws
      args:
        TAG: ${TAG:-3.3.10}
    user: ${ELEMENTS_UID}:${ELEMENTS_GID}
    depends_on:
      - mongo
    networks:
      - elements
    ports:
      - "8080:8080"
    volumes:
      - ${CDN_REPOS_DIR:-./volume/repos/cdn-repos}:/opt/elements/cdn-repos
      - ${SCRIPT_REPOS_DIR:-./volume/repos/script-repos}:/opt/elements/script-repos
      - ${WS_LOG_DIR:-./volume/ws/log}:/var/log/elements
      - ${WS_CONF_DIR:-./volume/ws/conf}:/opt/elements/conf:ro
      - ${WS_CLASSPATH_DIR:-./volume/ws/classpath}:/opt/elements/classpath:ro

networks:
  elements:
